# Generated by Django 3.2.12 on 2022-03-25 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploadsongs', '0003_songuploads_songalbum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('songfileid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadsongs.songuploads')),
            ],
            options={
                'db_table': 'Favourites',
            },
        ),
    ]
