# Generated by Django 3.2.12 on 2022-03-24 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signupforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songtitle', models.CharField(max_length=200)),
                ('songtype', models.CharField(max_length=100)),
                ('songfile', models.FileField(upload_to='songs/')),
                ('songlyrics', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signupforms.registrations')),
            ],
            options={
                'db_table': 'SongUploads',
            },
        ),
    ]
