# Generated by Django 3.2.12 on 2022-03-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadsongs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songuploads',
            name='songlyrics',
            field=models.TextField(null=True),
        ),
    ]
