# Generated by Django 3.2.12 on 2022-03-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadsongs', '0002_alter_songuploads_songlyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='songuploads',
            name='songalbum',
            field=models.CharField(default='Album A', max_length=200),
        ),
    ]
